/*
 * Created on 2023-05-11 ( 16:30:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.example.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Employee"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="employee", schema="public" )
public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", length=200)
    private String     name ;

    @Column(name="experience")
    private Integer    experience ;

    @Column(name="designation", length=200)
    private String     designation ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Employee() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setExperience( Integer experience ) {
        this.experience = experience ;
    }
    public Integer getExperience() {
        return this.experience;
    }

    public void setDesignation( String designation ) {
        this.designation = designation ;
    }
    public String getDesignation() {
        return this.designation;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(experience);
        sb.append("|");
        sb.append(designation);
        return sb.toString(); 
    } 

}
